import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import GhostContentAPI from "@tryghost/content-api";

const api = new GhostContentAPI({
  url: "https://example-blog.digitalpress.blog",
  key: process.env.GHOST_API_KEY,
  version: "v3",
});

export const getStaticProps = async () => {
  const response = await api.posts.browse({
    include: "tags,authors",
  });

  return {
    props: {
      posts: response,
    },
  };
};

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Example Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto lg:max-w-2xl">
        <header className="mt-48">
          <h1 className="text-4xl text-gray-800 font-black">Example Blog</h1>
        </header>

        <div className="mt-12 space-y-4">
          {posts.map((post) => (
            <div key={post.id}>
              <Link href={`/${post.slug}`} passHref>
                <a>
                  <h2 className="text-xl text-gray-800 font-bold">
                    - {post.title}
                  </h2>
                </a>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
